baseURL: "https://federicoruggeri.github.io" 
title: Federico Ruggeri
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

menu:
    main:
        - name: Research
          url: research/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Teaching
          url: teaching/
          weight: 3
        - name: Software
          url: software/
          weight: 3
        - name: Tools
          url: tools/
          weight: 4 
        - name: Modding
          weight: 6

params:
    description: "Hello There! (~cit). Welcome to my personal website where you can find about my academic research, papers, teaching activities, programming tools, and various modding stuff. Cheers!"
    author: Federico Ruggeri
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research","papers","teaching","tools","modding"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Federico Ruggeri
          subtitle: "Hello There! (~cit). Welcome to my personal website where you can find about my academic research, papers, teaching activities, programming tools, and various modding stuff. Cheers!"
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: research/
            - name: Papers
              url: papers/
            - name: Teaching
              url: teaching/
            - name: Software
              url: software/
            - name: Tools
              url: tools/
            - name: Modding
              url: modding/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:federico.ruggeri6@unibo.it
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=moOd0BwAAAAJ
        - name: GitHub
          url: https://github.com/federicoruggeri

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Federico Ruggeri"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
